# -*- coding: utf-8 -*-
"""generate data for long ariphmetics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ent4Ys_0KbECFW4XS1SdCUUxAL7cbdkP
"""

import numpy as np
import pandas as pd
import os
import random
import time
import sys

max_digits = 10000
min_digits = 5
tests = 200
program_path = ''
data_file = 'data.csv'
out_dir = 'tests'
functions_order = ['Sum', 'Subtract', 'Multiplication2']


#sys.set_int_max_str_digits(50000)
# arr = []
# for i in range(len(functions_order)):
#   arr.append([])

# step = (max_digits - min_digits) // tests
# digitsN = min_digits
# while digitsN <= max_digits:
#   for i in range(len(functions_order)):
#     length = [digitsN, digitsN // 2, random.randint(digitsN // 2, digitsN), random.randint(digitsN // 2, digitsN)]
#     for digN in length:
#       n1 = random.randint(10 ** digitsN - 1, 10 ** (digitsN + 1))
#       n2 = random.randint(10 ** digN - 1, 10 ** (digN + 1))
#       op_i = i % len(functions_order)
#       operation = functions_order[op_i]
#       if operation == 'Subtract' and n1 < n2:
#         n1, n2 = n2, n1
#       t1 = time.monotonic()
#       res = 0
#       if operation == 'Sum':
#         res = n1 + n2
#       elif operation == 'Subtract':
#         res = n1 - n2
#       elif operation == 'Multiplication2':
#         res = n1 * n2
#       t2 = time.monotonic()
#       arr[op_i].append([n1, n2, operation, t2-t1, res])
#   digitsN += step

# arr2 = []
# for array in arr:
#   arr2 += array
# arr2 = np.asarray(arr2)
# pd.DataFrame(arr2).to_csv(data_file, index_label = "Index", header  = ['operand1', 'operand2', 'operation', 'time in python', 'result'])


i=0
questions = ''
last = 'no'
with open("./data.csv", 'r') as file:
  lines = file.read().split('\n')
  for line in lines:
    if line != '':
      line = line.split(',')
      if i == 0:
        pass
      else:
        if i == len(lines) - 2:
          last = 'yes'
        questions += line[1] + ' ' + line[2] + ' ' + line[3] + ' ' + last + '\n'
        f = open("correct/test{}.txt".format(line[0]), "w")
        f.write(line[5])
        f.close()
      i += 1
f = open("test.txt", "w")
f.write(questions)
f.close()

# import csv
# i=0
# string = "Index, L_op1, L_op2, operation, time in python \n"
# with open("./data.csv", 'r') as file:
#   csvreader = csv.reader(file)
#   for row in csvreader:
#     if i == 0:
#       pass
#     else:
#       string += row[0] + ', ' + str(len(row[1])) + ', ' + str(len(row[2])) + ', ' +  row[3] + ', ' +  row[4] + '\n' 
#     i += 1
# f = open("data_for_chart.csv".format(row[0]), "w")
# f.write(string)
# f.close()